### ISSUE TITLE
Are there any builds of this anywhere?

### ISSUE THREAD

**Issue by guysoft** [Freescale/chromium-imx#2]
Hey,
Are there any available builds of chromium-imx anywhere?
For example for armbian?

**Comment by angolini** [comment]
There is not build for chromium-imx available.

**Comment by guysoft** [comment]
Thanks for the reply, bit late tough
Back in 2016, would have been able to ship with with a build for what is now FullPageOS.
Still have a board here.

**Comment by otavio** [comment]
What is the project about?

**Comment by guysoft** [comment]
This is the project: https://github.com/guysoft/FullPageOS

Widely used Kiosk webpage for RaspberryPi, at the time I spoke to someone in SolidRun, but he is not longer an employee there. So This project kinda got stuck, also since Raspberrypi/Boardcom added rpi-chromium-mods which utilises the GPU on the Pi. Still I am all for more devices support.
