### ISSUE TITLE
Videos playing in browser not GPU accelerated

### ISSUE THREAD

**Issue by appcodr** [Freescale/chromium-imx#6]
Hi,

Im trying to play the videos on the Chromium browser in the [iMX6](https://www.variscite.com/products/system-on-module-som/cortex-a9/var-som-mx6-cpu-freescale-imx6/) 

and currently the videos are not using the GPU to accelerate nd hte video paly is not smooth.  And when playing hte video you can see the chromium browser is using lot of CPU. Is there any option to enable GPU acceleration for the videos in the browser? I am launching the chromium using this script

```
#!/bin/sh
/usr/bin/chromium --use-gl=egl --gpu-no-context-lost --ignore-gpu-blacklist  $@

```

**top output**

```
top - 14:05:25 up 8 min,  2 users,  load average: 3.54, 1.97, 0.85
Tasks: 195 total,   2 running, 193 sleeping,   0 stopped,   0 zombie
%Cpu(s): 51.9 us,  8.6 sy,  0.3 ni, 38.7 id,  0.1 wa,  0.0 hi,  0.3 si,  0.0 st
KiB Mem :  1024192 total,   252644 free,   410568 used,   360980 buff/cache
KiB Swap:        0 total,        0 free,        0 used.   537212 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
 1457 x_user    20   0  479048 151392  95648 S 186.3 14.8   4:14.74 chromium
 1333 x_user    20   0 1137408 118396  84732 S  20.6 11.6   2:29.89 chromium
  457 root      20   0  326532  35972  26380 R  13.4  3.5   2:55.33 Xorg
```

**Comment by angolini** [comment]
Could you, please, test using the latest version and update the status @appcodr
